### ISSUE TITLE
extractNameFromTemplate

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#1]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/01-strings-tasks.js#L72-L73
Можно сделать раза в 3 котороче.
RTFM: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice

**Comment by dm-grinko** [comment]
return value.slice(7, -1);
