### ISSUE TITLE
roundToPowerOfTen

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#10]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/02-numbers-tasks.js#L186

Выражение `Math.pow(10, pow)` вычисляется дважды. Быстрее будет вычислить один раз и сохранить в переменную.

**Comment by dm-grinko** [comment]
var a = Math.pow(10, pow);
    return Math.round(num / a) * a;
