### ISSUE TITLE
generateOdds

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#12]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L41-L46

RTFM: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by dm-grinko** [comment]
return Array.from({ length: len }, (v, k) => k * 2 + 1);
