### ISSUE TITLE
removeFalsyValues

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#14]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L117-L121

Тут тоже функция в filter кривоватая, внутри filter функция должна возвращать булевское значение:  true - если элеиент включается, и false - если исключается.

**Comment by dm-grinko** [comment]
return arr.filter(v => v);
