### ISSUE TITLE
toCsvText

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#15]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L223-L228

RTFM: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join

**Comment by dm-grinko** [comment]
return arr.join('\n');
