### ISSUE TITLE
propagateItemsByPositionIndex

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#17]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L306-L310

Подход правильный, но надо сделать одним выражением, без `return` внутри.

**Comment by dm-grinko** [comment]
return arr.reduce((a,b,index) => a.concat((new Array(index + 1)).fill(b)),[]);
