### ISSUE TITLE
get3TopItems

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#18]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L329

Это формальное решение. Да, юнит-тесты проходят. Но если  взять в качестве тестового массив
[ 1, 10, 2, 9, 3, 8 ], то работать не будет.

**Comment by dm-grinko** [comment]
return arr.sort((a,b) => b - a).slice(0,3);
