### ISSUE TITLE
getPositivesCount

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#19]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L346-L352

Создание промежуточного массива - это затраты на память и время. Можно же за один проход все просчитать. Это типичная задача для reduce - когда из массива нужно получить какое-то аггрегированное значение.

**Comment by dm-grinko** [comment]
return arr.reduce((a,b) => b > 0 ? a+1 : b, 0);
