### ISSUE TITLE
getItemsSum

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#21]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L390

От проверки на пустой массив можно избавиться, если в reduce добавить аргумент initialValue

**Comment by dm-grinko** [comment]
return arr.reduce((a, b) => a + b, 0);
