### ISSUE TITLE
sortCitiesArray

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#23]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L472-L474

Если честно, то не понимаю почему это вообще работает.  Но тут будут трудности, если понадобиться добавить еще пару полей для сравнения. Можно сделать вообще без тернарной операции.
RTFM: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

**Comment by dm-grinko** [comment]
function sortCitiesArray(arr) {
    var fields = ['country', 'city'];
    return arr.sort((a, b) => {
        var ind = fields.findIndex((field) => a[field].localeCompare(b[field]));
        return ind >= 0 ? a[fields[ind]].localeCompare(b[fields[ind]]) : 0;
    });
}
