### ISSUE TITLE
getIdentityMatrix

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#24]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L496-L501

Можно сделать без splice (это копирование данных туда-сюда).
RTFM: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by dm-grinko** [comment]
return Array(end - start + 1).fill(start).map(function(e, i) {return e + i});
