### ISSUE TITLE
getIntervalArray

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#25]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L518

Тут тоже с Array.from короче и нагляднее будет.

**Comment by dm-grinko** [comment]
return Array.from({length: end - start +1}, (v, k) => start + k);
