### ISSUE TITLE
selectMany

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#26]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L599-L602

Тут все правильно, только если не использовать промежуточную переменную `c`, то можно в одну строку записать с помощью arrow function.

**Comment by dm-grinko** [comment]
return arr.reduce((a, b) => a.concat(childrenSelector(b)),[]);
