### ISSUE TITLE
getElementByIndexes

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#27]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/04-arrays-tasks.js#L619-L622

Это хак, метод map используется как замена запрещенному forEach, а не как проекция массива на другой массив. По идеологии тут надо использовать reduce. Тогда сразу можно написать
```
return indexes.reduce(...);
```

**Comment by dm-grinko** [comment]
function getElementByIndexes(arr, indexes) {
    return indexes.reduce((a, b, i) => {

        if (i != indexes.length -1) {arr = arr[b];}

        else {return arr[b];}

        return null;

    }, null);
}
