### ISSUE TITLE
unbracketTag

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#4]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/01-strings-tasks.js#L149
Тут по условию нужно у тега убрать первый и последний символ. Метод slice будет и короче и быстрее.

**Comment by dm-grinko** [comment]
return str.slice(1, -1);
