### ISSUE TITLE
getCardId

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#6]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/01-strings-tasks.js#L281-L295
Идея c "A234567891JQK" правильная, так почему бы не замахнуться на большее и не сделать с мастями тоже самое, получиться в одну строку:
```
return '♣♦♥♠'.indexOf(value.slice(-1)) * 13 + ...
```

**Comment by dm-grinko** [comment]
return "A234567891JQK".indexOf(value.slice(0,1)) + "♣♦♥♠".indexOf(value.slice(-1))* 13;
