### ISSUE TITLE
getDistanceBetweenPoints

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#7]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/02-numbers-tasks.js#L78

RTFM https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot

**Comment by dm-grinko** [comment]
return Math.hypot((x2-x1), (y2-y1));
