### ISSUE TITLE
getLastDigit

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#8]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/02-numbers-tasks.js#L132

RTFM https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder

**Comment by dm-grinko** [comment]
return value % 10;
