### ISSUE TITLE
getParallelipidedDiagonal

### ISSUE THREAD

**Issue by aorgish** [dm-grinko/rolling-scopes-js-assignments#9]
https://github.com/dm-grinko/rolling-scopes-js-assignments/blob/a1efe499383282fee827bebf386932458ff869e3/task/02-numbers-tasks.js#L132

Тут уже не буду указывать, каким простым стандартным методом можно это сделать.

**Comment by dm-grinko** [comment]
return Math.hypot(a,b,c);
